{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thumbnail-service.fullname" . }}-config
  labels:
    {{- include "thumbnail-service.labels" . | nindent 4 }}
data:
  POSTGRES_SERVER: {{ include "thumbnail-service.postgresql.host" . | quote }}
  POSTGRES_PORT: {{ .Values.externalPostgresql.port | default "5432" | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  REDIS_HOST: {{ include "thumbnail-service.redis.host" . | quote }}
  REDIS_PORT: {{ .Values.externalRedis.port | default "6379" | quote }}
  MINIO_ENDPOINT: {{ include "thumbnail-service.minio.endpoint" . | quote }}
  MINIO_ORIGINALS_BUCKET: {{ .Values.minio.buckets.originals | quote }}
  MINIO_THUMBNAILS_BUCKET: {{ .Values.minio.buckets.thumbnails | quote }}
{{- end }}
