{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thumbnail-service.fullname" . }}-secret
  labels:
    {{- include "thumbnail-service.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.secretKey | b64enc | quote }}
{{- end }}
