apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thumbnail-service.fullname" . }}-server
  labels:
    {{- include "thumbnail-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "thumbnail-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "thumbnail-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
      {{- with .Values.server.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.server | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-postgresql
        image: postgres:15
        command:
        - sh
        - -c
        - |
          until pg_isready -h {{ include "thumbnail-service.fullname" . }}-postgresql -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready"
      - name: wait-for-redis
        image: redis:7-alpine
        command:
        - sh
        - -c
        - |
          until redis-cli -h {{ include "thumbnail-service.fullname" . }}-redis ping; do
            echo "Waiting for Redis..."
            sleep 2
          done
          echo "Redis is ready"
      - name: wait-for-minio
        image: minio/mc:latest
        env:
        - name: MC_CONFIG_DIR
          value: "/tmp/.mc"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "thumbnail-service.fullname" .)) }}
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "thumbnail-service.fullname" .)) }}
              key: MINIO_SECRET_KEY
        command:
        - sh
        - -c
        - |
          until mc --config-dir="$MC_CONFIG_DIR" alias set minio http://{{ include "thumbnail-service.fullname" . }}-minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" && mc --config-dir="$MC_CONFIG_DIR" ls minio/ >/dev/null 2>&1; do
            echo "Waiting for MinIO..."
            sleep 5
          done
          echo "MinIO is ready"
        volumeMounts:
        - name: mc-temp
          mountPath: /tmp
      volumes:
      - name: mc-temp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      containers:
      - name: server
        image: "{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
        imagePullPolicy: {{ .Values.image.server.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.existingConfigMap | default (printf "%s-config" (include "thumbnail-service.fullname" .)) }}
        - secretRef:
            name: {{ .Values.existingSecret | default (printf "%s-secret" (include "thumbnail-service.fullname" .)) }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthChecks.server.liveness.path }}
            port: http
            scheme: HTTP
          initialDelaySeconds: {{ .Values.healthChecks.server.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.server.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.server.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.server.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthChecks.server.readiness.path }}
            port: http
            scheme: HTTP
          initialDelaySeconds: {{ .Values.healthChecks.server.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.server.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.server.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.server.readiness.failureThreshold }}
        resources:
          {{- toYaml .Values.resources.server | nindent 10 }}
        volumeMounts:
        - name: logs
          mountPath: /app/logs
